<?php

/** @var \Magento\Quote\Model\Quote\Item $_item */
$item = $block->getItem();

/** @var \Magento\Catalog\Model\Product $product */
$product = $item->getProduct();

/** @var \Magento\Quote\Model\Quote $quote */
$quote = $item->getQuote();

$productType = $product->getTypeId();

$categoryName = '';

if ($category = $product->getCategory()) {
  $categoryName = $category->getName();
}

$viewModel = $block->getData('viewModel');

$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionCartOfferEnabled() && $isCurrencySupported;

$productSku = $product->getSku();
/** sanitizing to prevent whitespace and other abnormal characters from being used in a div id */
$sanitizedProductSku = preg_replace('/[^a-zA-Z0-9-_|]/', '',  $productSku);
?>

<?php if ($shouldRender) : ?>
  <div>
    <div class="product-protection-offer" id="product_protection_offer_<?= $sanitizedProductSku ?>"></div>
  </div>
  <script type="text/x-magento-init">
    {
        "#product_protection_offer_<?= $sanitizedProductSku ?>": {
            "simpleProductProtectionOffer": [
               {
                        "extendStoreUuid": "<?= $block
                                              ->getData('viewModel')
                                              ->getExtendStoreUuid() ?>",
                        "activeEnvironment": "<?= $block
                                                ->getData('viewModel')
                                                ->getActiveEnvironment() ?>",
                        "selectedProductSku": "<?= $product->getSku() ?>",
                        "selectedProductPrice": "<?= $product->getPrice() ?>",
                        "productCategory": "<?= $categoryName ?>",
                        "currencyCode": "<?= $currencyCode ?>"
                    }
            ]
        }
    }
</script>
<?php endif; ?>
