<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Generic */
/** @var $escaper \Magento\Framework\Escaper */

/** @var \Magento\Quote\Model\Quote\Item $_item */
$item = $block->getItem();

/** @var \Magento\Catalog\Model\Product $product */
$product = $item->getProduct();

/** @var \Magento\Quote\Model\Quote $quote */
$quote = $item->getQuote();

$productType = $product->getTypeId();

$viewModel = $block->getData('viewModel');
$categoryModel = $block->getData('categoryModel');

$categoryName = '';
$categories = $product->getCategoryIds();

if (count($categories) > 0) {
  $categoryName = $categoryModel->getCategoryNameById($categories[0]);
}

$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionCartOfferEnabled() && $isCurrencySupported;

$productSku = $product->getSku();
/** sanitizing to prevent whitespace and other abnormal characters from being used in a div id */
$sanitizedProductSku = preg_replace('/[^a-zA-Z0-9-_|]/', '',  $productSku);
?>

<?php if ($shouldRender) : ?>
  <div>
    <div class="product-protection-offer" id="product_protection_offer_<?= $escaper->escapeHtml($sanitizedProductSku) ?>"></div>
  </div>
  <script type="text/x-magento-init">
    {
        "#product_protection_offer_<?= $escaper->escapeJs($sanitizedProductSku) ?>": {
            "simpleProductProtectionOffer": [
               {
                        "extendStoreUuid": "<?= $escaper->escapeJs($block
                                              ->getData('viewModel')
                                              ->getExtendStoreUuid()) ?>",
                        "activeEnvironment": "<?= $escaper->escapeJs($block
                                                ->getData('viewModel')
                                                ->getActiveEnvironment()) ?>",
                        "selectedProductSku": "<?= $escaper->escapeJs($product->getSku()) ?>",
                        "selectedProductPrice": "<?= $escaper->escapeJs($product->getPrice()) ?>",
                        "productCategory": "<?= $escaper->escapeJs($categoryName) ?>",
                        "currencyCode": "<?= $escaper->escapeJs($currencyCode) ?>"
                    }
            ]
        }
    }
</script>
<?php endif; ?>
