<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getData('viewModel');
$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();
$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();
$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionMinicartOfferEnabled() && $isCurrencySupported;
?>

<?php if ($shouldRender) : ?>
  <div id="extendMinicartSimpleOffer"></div>
  <script type="text/x-magento-init">
    {
        "#extendMinicartSimpleOffer": {
            "minicartSimpleOffer": [
                {
                    "extendStoreUuid": "<?= $escaper->escapeJs($extendStoreUuid) ?>",
                    "activeEnvironment": "<?= $escaper->escapeJs($activeEnvironment) ?>",
                    "currencyCode": "<?= $escaper->escapeJs($currencyCode) ?>"
                }
            ]
        }
    }
  </script>
<?php endif; ?>
