<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */
$viewModel = $block->getData('viewModel');
$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();
$categoriesForMinicartProducts = $block->getData('categoriesForMinicartProducts');
$productsCategories = $categoriesForMinicartProducts->getProductCategories();
?>

<div id="extendMinicartSimpleOffer"></div>
<script type="text/x-magento-init">
    {
        "#extendMinicartSimpleOffer": {
            "minicartSimpleOffer": [
               {
                    "extendStoreUuid": "<?= $extendStoreUuid ?>",
                    "activeEnvironment": "<?= $activeEnvironment ?>",
                    "productsCategories": <?= json_encode($productsCategories) ?>
                }
            ]
        }
    }
</script>
