<?php
    $status = $block->getActiveIntegrationStatusOnStore();
    if ($status === 0): ?>
    <button class="finish_integration" name="finish_integration" type="button" onclick="document.location.href='<?=$block->getDefaultScopeUrl()?>';">
        <span><?=__('Finish Integration')?></span>
    </button>
    <p>The <strong><?= $this->getCurrentIntegrationName() ?></strong> integration is not yet enabled. Please follow the steps detailed on the <a href="<?=$block->getDefaultScopeUrl()?>">Extend Settings</a> page to complete
          your setup and integration this store with Extend.</p>
<?php elseif ($status === 1): ?>
    <p>The current integration is <strong><?= $this->getCurrentIntegrationName() ?></strong>.</p>
    <div>
      <input type="checkbox" name="activate_current_store" id="activate_current_store" />
      <label for="activate_current_store">Add Store to current Integration</label>
    </div>
<?php elseif ($status === 2): ?>
    <p>The current integration is <strong><?= $this->getCurrentIntegrationName() ?></strong>.</p>
    <div>
      <input type="checkbox" name="activate_current_store" id="activate_current_store" checked disabled />
      <label for="activate_current_store">Add Store to current Integration</label>
    </div>
<?php elseif ($status === 3): ?>
    <p>The Extend integration could not be found for the given store. Usually in this case an integration was selected and then deleted. Please
      go to the <a href="<?=$block->getDefaultScopeUrl()?>">Extend Settings</a> page and select a new integration.
    </p>
<?php elseif ($status === 4): ?>
    <p>Error retrieving the Extend integration for the given store.</p>
<?php endif; ?>
