<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var Extend\Integration\ViewModel\EnvironmentAndExtendStoreUuid $viewModel */

$viewModel = $block->getData('viewModel');
$shouldRender = $viewModel->isExtendShippingProtectionEnabled();
?>


<?php if ($shouldRender): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "checkoutCartTotalsSp": [{}]
        }
    }
</script>
<?php endif; ?>
