<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Extend\Integration\Block\Adminhtml\Sales\Order\Creditmemo\Totals $block */
$shippingProtectionPrice = $block->getShippingProtection();
if ($block->isSpgSpRemovedFromCreditMemo()) {
  $shippingProtectionPrice = '';
}
?>

<?php if ($block->getOriginalShippingProtection() > 0 || $block->isSpSpg()): ?>
    <tr>
        <td class="label">
            <?= $block->escapeHtml(__('Shipping Protection')) ?>
            <div id="shipping_protection_adv"></div>
            <div class="sp-buttons-container" id="extend_sp_buttons_container">
                <?php if ($block->isSpSpg()): ?>
                    <div>(Safe Package Guarantee)</div>
                    <button name="spg-add" type="button" class="zero" id="extend_sp_buttons_container__spg_add"><?=__('Add to Refund')?></button>
                    <button name="spg-remove" type="button" class="full" id="extend_sp_buttons_container__spg_remove"><?=__('Remove from Refund')?></button>
                <?php else: ?>
                    <button name="full" type="button" class="full" id="extend_sp_buttons_container__full"><?=__('Full')?></button>
                    <button name="zero" type="button" class="zero" id="extend_sp_buttons_container__zero"><?=__('0')?></button>
                <?php endif; ?>
            </div>
        </td>
        <td>
            <input type="text"
                name="creditmemo[shipping_protection]"
                data-full="<?= /* @noEscape */ $block->getOriginalShippingProtection() ?>"
                value="<?= /* @noEscape */ $shippingProtectionPrice ?>"
                class="input-text admin__control-text not-negative-amount"
                readonly="readonly"
                id="shipping_protection"/>
            <?php $scriptString = <<<script
                require(['prototype'], function(){

                //<![CDATA[
                Validation.addAllThese([
                    [
                        'not-negative-amount',
                        '{$block->escapeJs(__('Please enter a positive number in this field.'))}',
                        function (v) {
                            if (v.length)
                                return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                            else
                                return true;
                        }
                    ]
                ]);

                const spButtonsContainer = document.getElementById('extend_sp_buttons_container');
                const shippingProtectionInput = document.getElementById('shipping_protection');
                const updateTotalsButton = document.querySelectorAll('.update-totals-button')[0];

                const spgAdd = document.getElementById('extend_sp_buttons_container__spg_add');
                const spgRemove = document.getElementById('extend_sp_buttons_container__spg_remove');

                if (spgAdd && spgRemove) {
                    if (shippingProtectionInput.value === '0') {
                        spgAdd.style.display = "none";
                        spgRemove.style.display = "block";
                    } else {
                        spgAdd.style.display = "block";
                        spgRemove.style.display = "none";
                    }
                }

                if (spButtonsContainer && shippingProtectionInput) {
                    spButtonsContainer.addEventListener('click', (event) => {
                        if (event.target.id === 'extend_sp_buttons_container__full') {
                            shippingProtectionInput.value = shippingProtectionInput.getAttribute('data-full');
                        }
                        if (event.target.id === 'extend_sp_buttons_container__zero') {
                            shippingProtectionInput.value = 0;
                        }
                        if (event.target.id === 'extend_sp_buttons_container__spg_remove') {
                            shippingProtectionInput.value = '';
                            spgAdd.style.display = "block";
                            spgRemove.style.display = "none";
                        }
                        if (event.target.id === 'extend_sp_buttons_container__spg_add') {
                            shippingProtectionInput.value = 0;
                            spgAdd.style.display = "none";
                            spgRemove.style.display = "block";
                        }
                        if (
                            updateTotalsButton &&
                            (
                                event.target.id === 'extend_sp_buttons_container__zero' ||
                                event.target.id === 'extend_sp_buttons_container__full' ||
                                event.target.id === 'extend_sp_buttons_container__spg_remove' ||
                                event.target.id === 'extend_sp_buttons_container__spg_add'
                            )
                        ) {
                            updateTotalsButton.removeAttribute('disabled');
                            updateTotalsButton.classList.remove('disabled');
                        }
                    });
                }

                if ($('shipping_protection')) {
                    $('shipping_protection').adviceContainer = $('shipping_protection_adv');
                    unblockSubmit('shipping_protection');
                }

                function unblockSubmit(id) {
                    $(id).observe('focus', function(event) {
                        if ($$('button[class="scalable update-button disabled"]').size() > 0) {
                            enableElements('submit-button');
                        }
                    });
                    $(id).observe('change', function (event) {
                        enableElements('submit-button');
                    });
                }
                //]]>

                });
script;
            ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
        </td>
    </tr>
<?php endif; ?>
