<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Extend\Integration\Block\Adminhtml\Sales\Order\Creditmemo\Totals $block */

?>
<?php if ($block->getOriginalShippingProtection() > 0): ?>
    <tr>
        <td class="label">
            <?= $block->escapeHtml(__('Shipping Protection')) ?>
            <div id="shipping_protection_adv"></div>
            <div class="sp-buttons-container" id="extend_sp_buttons_container">
                <button name="full" type="button" class="full" id="extend_sp_buttons_container__full"><?=__('Full')?></button>
                <button name="zero" type="button" class="zero" id="extend_sp_buttons_container__zero"><?=__('0')?></button>
            </div>
        </td>
        <td>
            <input type="text"
                name="creditmemo[shipping_protection]"
                data-full="<?= /* @noEscape */ $block->getOriginalShippingProtection() ?>"
                value="<?= /* @noEscape */ $block->getShippingProtection() ?>"
                class="input-text admin__control-text not-negative-amount"
                readonly="readonly"
                id="shipping_protection"/>
            <?php $scriptString = <<<script
                require(['prototype'], function(){

                //<![CDATA[
                Validation.addAllThese([
                    [
                        'not-negative-amount',
                        '{$block->escapeJs(__('Please enter a positive number in this field.'))}',
                        function (v) {
                            if (v.length)
                                return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                            else
                                return true;
                        }
                    ]
                ]);
                
                const spButtonsContainer = document.getElementById('extend_sp_buttons_container');
                const shippingProtectionInput = document.getElementById('shipping_protection');
                const updateTotalsButton = document.querySelectorAll('.update-totals-button')[0];
                
                if (spButtonsContainer && shippingProtectionInput) {
                    spButtonsContainer.addEventListener('click', (event) => {
                        if (event.target.id === 'extend_sp_buttons_container__full') {
                            shippingProtectionInput.value = shippingProtectionInput.getAttribute('data-full');
                        }
                        if (event.target.id === 'extend_sp_buttons_container__zero') {
                            shippingProtectionInput.value = 0;
                        }
                        if (
                            updateTotalsButton && 
                            (
                                event.target.id === 'extend_sp_buttons_container__zero' || 
                                event.target.id === 'extend_sp_buttons_container__full'
                            )
                        ) {
                            updateTotalsButton.removeAttribute('disabled');
                            updateTotalsButton.classList.remove('disabled');
                        }
                    });
                }

                if ($('shipping_protection')) {
                    $('shipping_protection').advaiceContainer = $('shipping_protection_adv');
                    unblockSubmit('shipping_protection');
                }

                function unblockSubmit(id) {
                    $(id).observe('focus', function(event) {
                        if ($$('button[class="scalable update-button disabled"]').size() > 0) {
                            enableElements('submit-button');
                        }
                    });
                    $(id).observe('change', function (event) {
                        enableElements('submit-button');
                    });
                }
                //]]>

                });
script;
            ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
        </td>
    </tr>
<?php endif; ?>
