<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View|Magento\GroupedProduct\Block\Product\View\Type\Grouped */

$categoryName = '';

if ($category = $block->getProduct()->getCategory()) {
    $categoryName = $category->getName();
}

?>
<?php foreach ($block->getAssociatedProducts() as $product): ?>
    <div class="product-protection-offer" id="product_protection_offer_<?= $product->getSku(); ?>"></div>
<?php endforeach; ?>
<script type="text/x-magento-init">
    {
        "#product_protection_offer": {
            "productProtectionOffer": {
                "<?= $block->getProduct()->getSku(); ?>": {
                    "extendStoreUuid": "<?= $block->getData('viewModel')->getExtendStoreUuid() ?>",
                    "activeEnvironment": "<?= $block->getData('viewModel')->getActiveEnvironment() ?>",
                    "selectedProductSku": "<?= $block->getProduct()->getSku(); ?>",
                    "selectedProductPrice": "<?= $block->getProduct()->getPrice(); ?>",
                    "productCategory": "<?= $categoryName; ?>"
                }
            }
        }
    }
</script>
