<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block Magento\GroupedProduct\Block\Product\View\Type\Grouped */

$viewModel = $block->getData('viewModel');
$categoryModel = $block->getData('categoryModel');
$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();
$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionProductCatalogPageModalOfferEnabled() && $isCurrencySupported;
?>

<?php if ($shouldRender) : ?>
  <table id="product_protection_offers">
    <?php foreach ($block->getAssociatedProducts() as $product) : ?>
      <tr>
        <td class="product-protection-offer product-id-<?= $product->getEntityId(); ?>" id="product_protection_offer_<?= preg_replace('/[^a-zA-Z0-9-_|]/', '',  $product->getSku()); ?>" colspan="3" style="border-top: 0 !important"></td>
      </tr>
    <?php endforeach; ?>
  </table>
  <script type="text/x-magento-init">
    {
        "#product_protection_offers": {
            "productProtectionOffer": [
                <?php foreach ($block->getAssociatedProducts() as $key => $product) : ?>
                    <?
                      $categoryName = '';
                      $categories = $product->getCategoryIds();

                      if (count($categories) > 0) {
                        $categoryName = $categoryModel->getCategoryNameById($categories[0]);
                      }
                    ?>
                    {
                        "extendStoreUuid": "<?= $block->getData('viewModel')->getExtendStoreUuid() ?>",
                        "activeEnvironment": "<?= $block->getData('viewModel')->getActiveEnvironment() ?>",
                        "selectedProductSku": "<?= $product->getSku(); ?>",
                        "selectedProductPrice": "<?= $product->getPrice(); ?>",
                        "productCategory": "<?= $categoryName; ?>",
                        "currencyCode": "<?= $currencyCode ?>"
                    }<?= array_key_last($block->getAssociatedProducts()) === $key ? '' : ',' ?>
                <?php endforeach; ?>
            ]
        }
    }
  </script>
  <script type="text/javascript" src="<?= $block->getViewFileUrl('Extend_Integration::js/view/catalog/product/product-protection-grouped.js') ?>"></script>
<?php endif; ?>
