<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getData('viewModel');

$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();
$leadToken = $viewModel->getLeadTokenFromUrl();
$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionPostPurchaseLeadModalOfferEnabled() && $isCurrencySupported;
?>

<?php if ($shouldRender) : ?>
  <script type="text/x-magento-init">
    {
          "*": {
              "aftermarketProductProtectionModalOffer": [
                  {
                      "extendStoreUuid": "<?= $escaper->escapeJs($extendStoreUuid) ?>",
                      "activeEnvironment": "<?= $escaper->escapeJs($activeEnvironment) ?>",
                      "leadToken": "<?= $escaper->escapeJs($leadToken) ?>",
                      "currencyCode": "<?= $escaper->escapeJs($currencyCode) ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
