<?php
$viewModel = $block->getData('viewModel');

$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();

$leadToken = $escaper->escapeHtml($escaper->escapeJs($viewModel->getLeadTokenFromUrl()));
$viewModel = $block->getData('viewModel');

$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionPostPurchaseLeadModalOfferEnabled() && $isCurrencySupported;
?>

<?php if ($shouldRender) : ?>
  <script type="text/x-magento-init">
    {
          "*": {
              "aftermarketProductProtectionModalOffer": [
                  {
                      "extendStoreUuid": "<?= $extendStoreUuid ?>",
                      "activeEnvironment": "<?= $activeEnvironment ?>",
                      "leadToken": "<?= /* @noEscape */ $leadToken ?>",
                      "currencyCode": "<?= $currencyCode ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
