<?php
$viewModel = $block->getData('viewModel');

$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();

$leadToken = $escaper->escapeHtml($escaper->escapeJs($viewModel->getLeadTokenFromUrl()));
?>
<script type="text/x-magento-init">
  {
        "*": {
            "aftermarketProductProtectionModalOffer": [
                {
                    "extendStoreUuid": "<?= $extendStoreUuid ?>",
                    "activeEnvironment": "<?= $activeEnvironment ?>",
                    "leadToken": "<?= /* @noEscape */ $leadToken ?>"
                }
            ]
        }
    }
</script>
