<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getData('viewModel');
$categoryModel = $block->getData('categoryModel');

$categoryName = '';
$categories = $block->getProduct()->getCategoryIds();

if (count($categories) > 0) {
  $categoryName = $categoryModel->getCategoryNameById($categories[0]);
}

$product = $block->getProduct();
$productSku = $product->getSku();

/** sanitizing to prevent whitespace and other abnormal characters from being used in a div id */
$sanitizedProductSku = preg_replace('/[^a-zA-Z0-9-_|]/', '',  $productSku);

$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();
$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionProductDisplayPageOfferEnabled() && $isCurrencySupported;
?>

<?php if ($shouldRender) : ?>
  <div class="product-protection-offer" id="product_protection_offer_<?= $escaper->escapeHtml($sanitizedProductSku) ?>"></div>
  <script type="text/x-magento-init">
    {
          "#product_protection_offer_<?= $escaper->escapeJs($sanitizedProductSku) ?>": {
              "productProtectionOffer": [
                  {
                      "extendStoreUuid": "<?= $escaper->escapeJs($block->getData('viewModel')->getExtendStoreUuid()) ?>",
                      "activeEnvironment": "<?= $escaper->escapeJs($block->getData('viewModel')->getActiveEnvironment()) ?>",
                      "selectedProductSku": "<?= $escaper->escapeJs($block->getProduct()->getSku()); ?>",
                      "selectedProductPrice": "<?= $escaper->escapeJs($block->getProduct()->getPrice()); ?>",
                      "productCategory": "<?= $escaper->escapeJs($categoryName); ?>",
                      "currencyCode": "<?= $escaper->escapeJs($currencyCode) ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
