<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$categoryName = '';

if ($category = $block->getProduct()->getCategory()) {
  $categoryName = $category->getName();
}

$viewModel = $block->getData('viewModel');

$product = $block->getProduct();
$productSku = $product->getSku();

/** sanitizing to prevent whitespace and other abnormal characters from being used in a div id */
$sanitizedProductSku = preg_replace('/[^a-zA-Z0-9-_|]/', '',  $productSku);

$currencyCode = $viewModel->getCurrencyCode();
$isCurrencySupported = $viewModel->isCurrencySupported();
$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionProductDisplayPageOfferEnabled() && $isCurrencySupported;
?>

<?php if ($shouldRender) : ?>
  <div class="product-protection-offer" id="product_protection_offer_<?= $sanitizedProductSku ?>"></div>
  <script type="text/x-magento-init">
    {
          "#product_protection_offer_<?= $sanitizedProductSku ?>": {
              "productProtectionOffer": [
                  {
                      "extendStoreUuid": "<?= $block->getData('viewModel')->getExtendStoreUuid() ?>",
                      "activeEnvironment": "<?= $block->getData('viewModel')->getActiveEnvironment() ?>",
                      "selectedProductSku": "<?= $block->getProduct()->getSku(); ?>",
                      "selectedProductPrice": "<?= $block->getProduct()->getPrice(); ?>",
                      "productCategory": "<?= $categoryName; ?>",
                      "currencyCode": "<?= $currencyCode ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
