<?php
$viewModel = $block->getData('viewModel');

$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();

/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();

$productId = $product->getId();
$productPrice = $product->getPrice();

$categoryName = '';
if ($category = $product->getCategory()) {
    $categoryName = $category->getName();
}

?>

<div class="product_protection_modal_offer" id="product_protection_modal_offer"></div>

<script type="text/x-magento-init">
    {
        "#product_protection_modal_offer": {
            "productProtectionModalOffer": [
                {
                    "extendStoreUuid": "<?= $extendStoreUuid ?>",
                    "activeEnvironment": "<?= $activeEnvironment ?>",
                    "productId": "<?= $productId ?>",
                    "productPrice": "<?= $productPrice ?>",
                    "productCategory": "<?= $categoryName ?>"
                }
            ]
        }
    }
</script>
<script>
    console.log('Loaded template script');
</script>