<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$categoryName = '';
/** encoding to prevent whitespace and other abnormal characters from being used in a div id */
$encodedProductSku = urlencode($product->getSku());

if ($category = $block->getProduct()->getCategory()) {
    $categoryName = $category->getName();
}

?>

<div class="product-protection-offer" id="product_protection_offer_<?= $encodedProductSku; ?>"></div>
<script type="text/x-magento-init">
    {
        "#product_protection_offer_<?= $encodedProductSku; ?>": {
            "productProtectionOffer": [
                {
                    "extendStoreUuid": "<?= $block->getData('viewModel')->getExtendStoreUuid() ?>",
                    "activeEnvironment": "<?= $block->getData('viewModel')->getActiveEnvironment() ?>",
                    "selectedProductSku": "<?= $encodedProductSku; ?>",
                    "selectedProductPrice": "<?= $block->getProduct()->getPrice(); ?>",
                    "productCategory": "<?= $categoryName; ?>"
                }
            ]
        }
    }
</script>
